{{- if and .Values.controller.enabled .Values.controller.podDisruptionBudget.enabled (gt (int .Values.controller.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "scale-csi.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scale-csi.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  {{- if ne (toString .Values.controller.podDisruptionBudget.minAvailable) "" }}
  minAvailable: {{ .Values.controller.podDisruptionBudget.minAvailable }}
  {{- else if ne (toString .Values.controller.podDisruptionBudget.maxUnavailable) "" }}
  maxUnavailable: {{ .Values.controller.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  maxUnavailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "scale-csi.controllerSelectorLabels" . | nindent 6 }}
{{- end }}
