#!/usr/bin/env bash
# Regenerates pkg/util/testdata/iscsi-node-db from a node database that the REAL
# iscsiadm wrote, rather than one hand-drawn from someone's model of the format.
#
# Why this exists: iscsiNodeRecordFiles has to know which of open-iscsi's two
# node-record layouts a record uses, and that is not something to guess. A
# hand-drawn fixture that encoded only the new-style <host>,<port>,<tpgt>/<iface>
# DIRECTORY layout let a 100%-broken CHAP node-record write ship green, because
# `iscsiadm -m node -o new -T <iqn> -p <host>:<port>` (no tpgt) actually leaves
# the OLD-style layout: a plain FILE at nodes/<iqn>/<host>,<port>.
#
# open-iscsi has no --db-root / ISCSI_DB_ROOT override: idbm's root is the
# compiled-in /var/lib/iscsi. So run iscsiadm in a private mount namespace with a
# scratch directory bind-mounted over it. Needs unprivileged user namespaces
# (`unshare -Urm`) and an installed iscsiadm; it does NOT need root and never
# touches this host's real node database, iscsid, or any network.
#
# Usage: hack/capture-iscsi-node-db-fixture.sh [output-dir]
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
out=${1:-$repo_root/pkg/util/testdata/iscsi-node-db}
export PATH=/usr/sbin:/sbin:$PATH
command -v iscsiadm >/dev/null || { echo "iscsiadm not installed" >&2; exit 1; }

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
mkdir -p "$work/db"/{ifaces,isns,nodes,send_targets,static,slp} "$work/lock"

unshare -Urm --propagation private /bin/bash -euo pipefail -s "$work" <<'INNER'
work=$1
export PATH=/usr/sbin:/sbin:$PATH
mount --bind "$work/db" /var/lib/iscsi
mkdir -p /run/lock/iscsi 2>/dev/null || true
mount --bind "$work/lock" /run/lock/iscsi

fastpath="iqn.2005-10.org.freenas.ctl:pvc-fastpath"
discovered="iqn.2005-10.org.freenas.ctl:pvc-discovered"

# 1. Exactly the argv iscsiEnsureNodeRecord runs: no tpgt, so idbm records
#    PORTAL_GROUP_TAG_UNKNOWN (-1) and writes the OLD-style flat file. Three
#    portals: the one under test, an unrelated one, and an IPv6 one.
iscsiadm -m node -o new -T "$fastpath" -p 192.0.2.40:3260 >/dev/null
iscsiadm -m node -o new -T "$fastpath" -p 192.0.2.41:3260 >/dev/null
iscsiadm -m node -o new -T "$fastpath" -p '[2001:db8::31]:3260' >/dev/null

# 2. A portal given WITH a tpgt -- what a SendTargets discovery yields -- gets
#    the NEW-style <host>,<port>,<tpgt>/<iface> directory instead.
iscsiadm -m node -o new -T "$discovered" -p 192.0.2.40:3260,1 >/dev/null
iscsiadm -m node -o new -T "$discovered" -p 192.0.2.41:3260,1 >/dev/null

# 3. Bind a second iface so one directory record carries two iface files: a
#    --login may use either, so a credential write has to reach both.
iscsiadm -m iface -o new -I iface1 >/dev/null
iscsiadm -m node -o new -T "$discovered" -p 192.0.2.40:3260,1 -I iface1 >/dev/null

cp -a /var/lib/iscsi/nodes "$work/captured"
INNER

rm -rf "$out"
mkdir -p "$out/tree"
cp -a "$work/captured" "$out/tree/nodes"

{
  echo "# Modes as captured, recorded here because git carries only the exec bit."
  echo "# Columns: type mode path (relative to tree/)."
  (cd "$out/tree" && find . -mindepth 1 -printf '%y %m %P\n' | sort)
} >"$out/MANIFEST"

version=$(iscsiadm --version)
package=$(rpm -q iscsi-initiator-utils 2>/dev/null || echo "unknown package")
cat >"$out/README.md" <<README
# Real open-iscsi node database (test fixture)

Generated by \`hack/capture-iscsi-node-db-fixture.sh\`. **Do not hand-edit.**
If a test disagrees with this tree, regenerate the tree and fix the code or the
test -- never adjust the fixture to match what the code expects. A hand-drawn
predecessor of this fixture is exactly how a wholly non-functional CHAP
node-record write shipped green.

- Producer: \`$version\` (\`$package\`), which is open-iscsi 2.1.11, the version
  running on this cluster's nodes.
- Captured $(date -u +%Y-%m-%d) in a private mount namespace with a scratch
  directory bind-mounted over \`/var/lib/iscsi\`. No network, no iscsid, no root.

## What it pins down

\`iscsiadm -m node -o new -T <iqn> -p <host>:<port>\` -- the exact argv
\`iscsiEnsureNodeRecord\` runs -- passes no target portal group tag, so idbm
records \`PORTAL_GROUP_TAG_UNKNOWN\` (-1) and writes the **old-style** record: a
plain **file** at \`nodes/<iqn>/<host>,<port>\` (see
\`nodes/iqn.2005-10.org.freenas.ctl:pvc-fastpath/\`).

A portal given WITH a tpgt (\`-p <host>:<port>,<tpgt>\`, which is what a
SendTargets discovery yields) instead produces the **new-style**
\`nodes/<iqn>/<host>,<port>,<tpgt>/<iface>\` **directory**, one file per bound
iface (see \`nodes/iqn.2005-10.org.freenas.ctl:pvc-discovered/\`, which carries
both \`default\` and \`iface1\`).

The two layouts are mutually exclusive for one (target, host, port): running
\`-o new\` with a tpgt over an existing flat record MIGRATES it to the directory
layout, and a later \`-o new\` without a tpgt reports "using tpgt 1 from existing
record" and leaves the directory in place. So a node that has ever run a
discovery for a target is on the directory layout, and a node that has only ever
run this driver's fast path is on the flat one. Both occur in the field.

An IPv6 portal is recorded **without** brackets: \`2001:db8::31,3260\`.

Every record file was created \`0600\` and every directory \`0700\`, at both
\`umask 022\` and \`umask 000\` -- see \`MANIFEST\`. Tests deliberately materialize
the tree LOOSER than that, so asserting the credential write installs 0600
proves a tightening rather than an inherited default.
README

echo "wrote $out"
(cd "$out" && find . -type f | sort)
