#!/bin/bash

# Wrapper script that decides whether to run mount in container or on host.
# We parse -t (filesystem type) to detect filesystems that require host tools.
# All other options are passed through to mount unchanged.

container_supported_filesystems=(
  "ext2"
  "ext3"
  "ext4"
  "ext4dev"
  "btrfs"
  "xfs"
  "vfat"
  "nfs"
  "nfs3"
  "nfs4"
  "cifs"
  "smb"
  "smb3"
  "bind"
)

# Parse options we care about, ignore others
# t: = filesystem type (we check if it needs host tools)
# o: = mount options (ignored, just need to accept it)
# Other common mount options: n, r, w, v, f, a
while getopts ":t:o:nrwvfa" opt; do
  case "$opt" in
    t)
      if [[ "x${USE_HOST_MOUNT_TOOLS}" == "x" ]]; then
        [[ "${OPTARG,,}" == "zfs" ]] && USE_HOST_MOUNT_TOOLS=1
        [[ "${OPTARG,,}" == "lustre" ]] && USE_HOST_MOUNT_TOOLS=1
        [[ "${OPTARG,,}" == "onedata" ]] && USE_HOST_MOUNT_TOOLS=1
      fi
      ;;
    # All other options are accepted but ignored (passed through to mount)
    *) ;;
  esac
done

if [[ ${USE_HOST_MOUNT_TOOLS} -eq 1 ]]; then
  # Use direct path for compatibility with minimal OS like Talos
  chroot /host /bin/mount "$@"
else
  /bin/mount "$@"
fi
