#!/bin/bash

while getopts ":t:l" opt; do
  case "$opt" in
    t)
      if [[ "x${USE_HOST_MOUNT_TOOLS}" == "x" ]]; then
        [[ "${OPTARG,,}" == "zfs" ]] && USE_HOST_MOUNT_TOOLS=1
        [[ "${OPTARG,,}" == "lustre" ]] && USE_HOST_MOUNT_TOOLS=1
        [[ "${OPTARG,,}" == "onedata" ]] && USE_HOST_MOUNT_TOOLS=1
      fi
      ;;
  esac
done

if [[ ${USE_HOST_MOUNT_TOOLS} -eq 1 ]]; then
  # Use direct path for compatibility with minimal OS like Talos
  chroot /host /bin/umount "${@:1}"
else
  /bin/umount "${@:1}"
fi
